### ISSUE TITLE
XML error when installing this Language pack

### ISSUE THREAD

**Issue by GrimLink** [magento-l10n/language-nl_DI#1]
```
The XML in file "~/projects/magento/m23/vendor/community-engineering/language-nl_di/language.xml" is invalid:
Element 'code': [facet 'pattern'] The value 'nl_di' is not accepted by the pattern '[a-z]{2}_([a-zA-Z]{4}_)?[A-Z]{2}'. Line: 9
Element 'code': 'nl_di' is not a valid value of the atomic type 'codeType'. Line: 9 Verify the XML and try again.
```

In every language package the code and package values are (from the nl_NL):
_The error is only for the code value._

- code = nl_NL
- package = nl_NL

So in here it should be:

- code = nl_NL
- package = nl_DI

**Comment by peterjaap** [comment]
We have solved this for now by using this patch to use with `vaimo/composer-patches`:

```
$ cat patches/community-engineering/language-nl_di/use-informal-translation.patch 


@package community-engineering/language-nl_di
@level 0

diff --git language.xml language.xml
index 6047180..11a7381 100644
--- language.xml
+++ language.xml
@@ -6,7 +6,7 @@
  */
 -->
 <language xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/Language/package.xsd">
-    <code>nl_di</code>
+    <code>nl_NL</code>
     <vendor>CommunityEngineering</vendor>
-    <package>nl_di</package>
+    <package>nl_NL</package>
 </language>
diff --git nl_di.csv nl_NL.csv
similarity index 100%
rename from nl_di.csv
rename to nl_NL.csv
diff --git registration.php registration.php
index 2e87262..81d591c 100644
--- registration.php
+++ registration.php
@@ -7,4 +7,4 @@ declare(strict_types=1);

 use \Magento\Framework\Component\ComponentRegistrar;

-ComponentRegistrar::register(ComponentRegistrar::LANGUAGE, 'communityengineering_nl_di', __DIR__);
+ComponentRegistrar::register(ComponentRegistrar::LANGUAGE, 'communityengineering_nl_nl', __DIR__);
```

**Comment by peterjaap** [comment]
Or you could use this in your `composer.json` or composer patches file;

```
    "community-engineering/language-nl_di": {
      "Change nl_di to nl_nl": {
        "source": "https://patch-diff.githubusercontent.com/raw/magento-l10n/language-nl_di/pull/2.patch",
        "link": "https://github.com/magento-l10n/language-nl_di/issues/1",
        "level": 1
      }
    }
```

**Comment by ArjenMiedema** [comment]
@GrimLink that is correct as nl_di is not a standard locale code, but an informal version of the Dutch translation pack. The reason why this is not set to nl_nl, is that this is already taken by the formal Dutch language pack. As mentioned by @peterjaap, adding that code to the composer patches, this should be working as expected.

This code comes straight from Crowdin and I don't think there's a layer in between that makes it possible to set a custom language code before making it a Composer package.

**Comment by GrimLink** [comment]
@peterjaap and @ArjenMiedema thank you, this solves the issue for me.
I already started using a personal fork, for work.
But that sadly that required me to keep it up to date with this package manually, so this solution will make it al lot easier.

I will use @peterjaap's solution as the solution for this issue 😉
